/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.g4.view;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import com.g4.repository.impl.DungTichRepo;
import com.g4.entity.DungTich;
import com.g4.utils.Utility;
import java.util.ArrayList;
/**
 *
 * @author khuong duc
 */
public class DungTichJPanel extends javax.swing.JFrame {

    private DungTichRepo dtrepo = new DungTichRepo();
    private List<DungTich> listDT = new ArrayList<>();

    private Utility uti = new Utility();
    
    private DefaultTableModel modeldt = new DefaultTableModel();
    private String dungtich ="";
    /**
     * Creates new form DungTichJPanel
     */
    public DungTichJPanel(java.awt.Frame parent, boolean modal) {
        initComponents();
        modeldt = (DefaultTableModel) tbl_ttdungtich.getModel();
        tbl_ttdungtich.setModel(modeldt);
        showData(listDT = dtrepo.getDungTich());
    }

    private void showData(List<DungTich> list){
        modeldt.setRowCount(0);
        
        for(DungTich dt : list){
            Object[] data = new Object[]{
                dt.getId(),dt.getDungtich()
            };
            modeldt.addRow(data);
        }
    }
    private void filldata(){
        List<DungTich> ms = dtrepo.getDungTich();
        modeldt.setRowCount(0);
        for (DungTich object : dtrepo.getDungTich()) {
            modeldt.addRow(new Object[]{object.getId(), object.getDungtich()});
        }
        
    }
    private String getDT(int i){
        try {
            String ten="";
            ten=txt_ttDT.getText().trim();
            
            if(ten.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Nhap mau");
                return null;
            }else {
                return ten;
            }
            
        } catch (Exception e) {
            return null;
        }
        
    }
    
    
    public String getDungTich(){
        return dungtich;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpndungtich = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ttdungtich = new javax.swing.JTable();
        lbl_dungtich = new javax.swing.JLabel();
        btn_ttThemDT = new javax.swing.JButton();
        btn_ttClearDT = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_ttDT = new javax.swing.JTextField();
        txtdtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpndungtich.setBackground(new java.awt.Color(204, 204, 204));

        tbl_ttdungtich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Dung tích"
            }
        ));
        tbl_ttdungtich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ttdungtichMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ttdungtich);

        lbl_dungtich.setText("Dung tích");

        btn_ttThemDT.setText("Thêm");
        btn_ttThemDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ttThemDTActionPerformed(evt);
            }
        });

        btn_ttClearDT.setText("Làm mới");
        btn_ttClearDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ttClearDTActionPerformed(evt);
            }
        });

        jLabel23.setText("ID: ");

        jLabel24.setText("Dung tích: ");

        txtdtID.setText("_ _");

        javax.swing.GroupLayout jpndungtichLayout = new javax.swing.GroupLayout(jpndungtich);
        jpndungtich.setLayout(jpndungtichLayout);
        jpndungtichLayout.setHorizontalGroup(
            jpndungtichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpndungtichLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jpndungtichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ttThemDT)
                    .addComponent(btn_ttClearDT))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpndungtichLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_dungtich)
                .addGap(167, 167, 167))
            .addGroup(jpndungtichLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jpndungtichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpndungtichLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpndungtichLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(23, 23, 23)))
                .addGroup(jpndungtichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ttDT, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpndungtichLayout.setVerticalGroup(
            jpndungtichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpndungtichLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dungtich, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jpndungtichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtdtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpndungtichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt_ttDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpndungtichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpndungtichLayout.createSequentialGroup()
                        .addComponent(btn_ttThemDT)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ttClearDT)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jpndungtich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpndungtich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_ttdungtichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ttdungtichMouseClicked
        // TODO add your handling code here:
        int vitri = tbl_ttdungtich.getSelectedRow();
        txtdtID.setText(String.valueOf(dtrepo.getDungTich().get(vitri).getId()));
        txt_ttDT.setText(dtrepo.getDungTich().get(vitri).getDungtich());
    }//GEN-LAST:event_tbl_ttdungtichMouseClicked

    private void btn_ttThemDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ttThemDTActionPerformed
        // TODO add your handling code here:
        String tenMau = getDT(1);
        if(tenMau!=null){
            try {
                dtrepo.themDungTich(tenMau);
            } catch (Exception e) {
            }
            filldata();
            
        }
    }//GEN-LAST:event_btn_ttThemDTActionPerformed

    private void btn_ttClearDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ttClearDTActionPerformed
        // TODO add your handling code here:
        txtdtID.setText("_ _");
        txt_ttDT.setText("");
    }//GEN-LAST:event_btn_ttClearDTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DungTichJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DungTichJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DungTichJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DungTichJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DungTichJPanel dialog = new DungTichJPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ttClearDT;
    private javax.swing.JButton btn_ttThemDT;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpndungtich;
    private javax.swing.JLabel lbl_dungtich;
    private javax.swing.JTable tbl_ttdungtich;
    private javax.swing.JTextField txt_ttDT;
    private javax.swing.JTextField txtdtID;
    // End of variables declaration//GEN-END:variables
}
