/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.g4.view;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import com.g4.repository.impl.HieuUngRepo;
import com.g4.entity.HieuUng;
import com.g4.utils.Utility;
import java.util.ArrayList;
/**
 *
 * @author khuong duc
 */
public class HieuUngJPanel extends javax.swing.JFrame {

    private HieuUngRepo hurepo = new HieuUngRepo();
    private List<HieuUng> listHU = new ArrayList<>();
    private DefaultTableModel modelhu = new DefaultTableModel();
    private Utility uti = new Utility();
    private String hieuung="";
    /**
     * Creates new form HieuUngJPanel
     */
    public HieuUngJPanel(java.awt.Frame parent, boolean modal) {
        initComponents();
        modelhu = (DefaultTableModel) tbl_tthieuung.getModel();
        tbl_tthieuung.setModel(modelhu);
        showData(listHU = hurepo.getHieuUng());
    }

    private void showData(List<HieuUng> list){
        modelhu.setRowCount(0);
        
        for(HieuUng hu : list){
            Object[] data = new Object[]{
                hu.getId(),hu.getTenhieuung()
            };
            modelhu.addRow(data);
        }
    }
     private void filldata(){
        List<HieuUng> ms = hurepo.getHieuUng();
        modelhu.setRowCount(0);
        for (HieuUng object : hurepo.getHieuUng()) {
            modelhu.addRow(new Object[]{object.getId(), object.getTenhieuung()});
        }
        
    }
    private String getHU(int i){
        try {
            String ten="";
            ten=txt_ttHU.getText().trim();
            
            if(ten.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Nhap hieu ");
                return null;
            }else {
                return ten;
            }
            
        } catch (Exception e) {
            return null;
        }
        
    }
    
    public String getHieuUng(){
        return hieuung;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnhieuung = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_tthieuung = new javax.swing.JTable();
        lbl_hieuung = new javax.swing.JLabel();
        btnthemHU = new javax.swing.JButton();
        btn_ttClearHU = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_ttHU = new javax.swing.JTextField();
        txthuID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnhieuung.setBackground(new java.awt.Color(204, 204, 204));

        tbl_tthieuung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Hiệu ứng"
            }
        ));
        tbl_tthieuung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tthieuungMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_tthieuung);

        lbl_hieuung.setText("Hiệu ứng");

        btnthemHU.setText("Thêm");
        btnthemHU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemHUActionPerformed(evt);
            }
        });

        btn_ttClearHU.setText("Làm mới");
        btn_ttClearHU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ttClearHUActionPerformed(evt);
            }
        });

        jLabel20.setText("ID: ");

        jLabel21.setText("Hiệu ứng: ");

        txthuID.setText("_ _");

        javax.swing.GroupLayout jpnhieuungLayout = new javax.swing.GroupLayout(jpnhieuung);
        jpnhieuung.setLayout(jpnhieuungLayout);
        jpnhieuungLayout.setHorizontalGroup(
            jpnhieuungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnhieuungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpnhieuungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnthemHU)
                    .addComponent(btn_ttClearHU))
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(jpnhieuungLayout.createSequentialGroup()
                .addGroup(jpnhieuungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnhieuungLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(lbl_hieuung))
                    .addGroup(jpnhieuungLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jpnhieuungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnhieuungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ttHU, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnhieuungLayout.setVerticalGroup(
            jpnhieuungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnhieuungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_hieuung, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jpnhieuungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txthuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnhieuungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_ttHU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnhieuungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnhieuungLayout.createSequentialGroup()
                        .addComponent(btnthemHU)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ttClearHU)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jpnhieuung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnhieuung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_tthieuungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tthieuungMouseClicked
        // TODO add your handling code here:
        int vitri = tbl_tthieuung.getSelectedRow();
        txthuID.setText(String.valueOf(hurepo.getHieuUng().get(vitri).getId()));
        txt_ttHU.setText(hurepo.getHieuUng().get(vitri).getTenhieuung());
    }//GEN-LAST:event_tbl_tthieuungMouseClicked

    private void btnthemHUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemHUActionPerformed
        // TODO add your handling code here:
        String tenHU = getHU(1);
        if(tenHU!=null){
            try {
                hurepo.themHieuUng(tenHU);
            } catch (Exception e) {
            }
            filldata();
            
        }
    }//GEN-LAST:event_btnthemHUActionPerformed

    private void btn_ttClearHUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ttClearHUActionPerformed
        // TODO add your handling code here:
        txthuID.setText("_ _");
        txt_ttHU.setText("");
    }//GEN-LAST:event_btn_ttClearHUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HieuUngJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HieuUngJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HieuUngJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HieuUngJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HieuUngJPanel dialog = new HieuUngJPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ttClearHU;
    private javax.swing.JButton btnthemHU;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpnhieuung;
    private javax.swing.JLabel lbl_hieuung;
    private javax.swing.JTable tbl_tthieuung;
    private javax.swing.JTextField txt_ttHU;
    private javax.swing.JTextField txthuID;
    // End of variables declaration//GEN-END:variables
}
