/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.g4.view;

import javax.swing.table.DefaultTableModel;
import com.g4.entity.HoaDon;
import com.g4.entity.HoaDonChiTiet;
import com.g4.viewmodel.HoaDonViewModel;
import java.util.ArrayList;
import java.util.List;
import com.g4.repository.impl.HoaDonRepository;
import com.g4.repository.impl.HDCTRepository;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author tuphp
 */
public class HoaDonJPanel extends javax.swing.JPanel {

    private DefaultTableModel dtm = new DefaultTableModel();
    private HoaDonRepository hdrepo = new HoaDonRepository();
    private HDCTRepository hdctrepo = new HDCTRepository();
    
    int trangthaiHD=1;
    int trangthaiHD2=3;
    /**
     * Creates new form HoaDonJPanel
     */
    public HoaDonJPanel()  {
        initComponents();
        try {
            loadDataHD();
        } catch (SQLException ex) {
            Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadDataHD() throws SQLException {
        List<HoaDon> list = hdrepo.selectAll2(tukhoatimkiem, trangthaiHD, trangthaiHD2);
        dtm = (DefaultTableModel) tbl_HD.getModel();
        dtm.setRowCount(0);
        for (HoaDon x : list) {
            dtm.addRow(new Object[]{
                 x.getMaHD(), x.getNgayTao(), x.getNgayThanhToan(), x.getTongTien(), x.getGhiChu(), x.getTrangThai(), x.getHTTT(),x.getIdNV()
            });
        }

    }
    public void loadDataHDCT(List<HoaDonChiTiet> lis) {
        
        dtm = (DefaultTableModel) tbl_HDCT.getModel();
        dtm.setRowCount(0);
        try {
            for (HoaDonChiTiet x : lis) {
            dtm.addRow(new Object[]{
                x.getIdHD(), x.getIdHD(), x.getSoLuong(), x.getDonGia()
            });
        }
        } catch (Exception e) {
        }

    }
    
    String tukhoatimkiem = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbo_locHD = new javax.swing.JComboBox<>();
        lbl_loc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HDCT = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_HD = new javax.swing.JTable();
        btn_timKiem = new javax.swing.JButton();
        txt_timKiem = new javax.swing.JTextField();
        lblHoaDon = new javax.swing.JLabel();
        lbl_HDCT = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        cbo_locHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đã thanh toán", "Đang chờ" }));
        cbo_locHD.setToolTipText("Lọc");

        lbl_loc.setText("LỌC");

        tbl_HDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID HÓA ĐƠN", "ID SẢN PHẨM", "SỐ LƯỢNG", "ĐƠN GIÁ"
            }
        ));
        jScrollPane1.setViewportView(tbl_HDCT);

        tbl_HD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HÓA ĐƠN", "NGÀY TẠO", "NGÀY THANH TOÁN", "TỔNG TIỀN", "GHI CHÚ", "TRẠNG THÁI", "HTTT", "ID NHAN VIEN"
            }
        ));
        tbl_HD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_HD);

        btn_timKiem.setBackground(new java.awt.Color(255, 255, 204));
        btn_timKiem.setText("TÌM KIẾM");
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        lblHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHoaDon.setText("HÓA ĐƠN");

        lbl_HDCT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_HDCT.setText("HÓA ĐƠN CHI TIẾT");

        jButton1.setText("Làm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cbo_locHD, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_loc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_timKiem)
                            .addGap(31, 31, 31)
                            .addComponent(jButton1)
                            .addGap(121, 121, 121))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHoaDon)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_HDCT))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_timKiem)
                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_locHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_loc)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbl_HDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_HDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HDMouseClicked
        // TODO add your handling code here:
        try {
            int vitri = tbl_HD.getSelectedRow();
            //JOptionPane.showMessageDialog(this, hdrepo.selectAll().get(vitri).getId());
            String hoadonthuN = hdrepo.selectAll().get(vitri).getId();
            List<HoaDonChiTiet> lisHDCT = hdctrepo.selectByHoaDon(Integer.parseInt(hoadonthuN));
            
            loadDataHDCT(lisHDCT);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tbl_HDMouseClicked
    
    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        tukhoatimkiem = txt_timKiem.getText().trim();
        if(cbo_locHD.getSelectedItem().equals("Đã thanh toán")){
            trangthaiHD=3;
             trangthaiHD2=3;
        }
        else if(cbo_locHD.getSelectedItem().equals("Đang chờ")){
            trangthaiHD=1;
             trangthaiHD2=1;
        }
        else{
             trangthaiHD=1;
             trangthaiHD2=3;
        }
        
        try {
            loadDataHD();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            loadDataHD();
        } catch (SQLException ex) {
            Logger.getLogger(HoaDonJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JComboBox<String> cbo_locHD;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lbl_HDCT;
    private javax.swing.JLabel lbl_loc;
    private javax.swing.JTable tbl_HD;
    private javax.swing.JTable tbl_HDCT;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
