/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.g4.view;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import com.g4.repository.impl.KetCauRepo;
import com.g4.entity.KetCau;
import com.g4.utils.Utility;
import java.util.ArrayList;
/**
 *
 * @author khuong duc
 */
public class KetCauJPanel extends javax.swing.JFrame {

    private KetCauRepo kcrepo = new KetCauRepo();
    private List<KetCau> listKC = new ArrayList<>();
    private Utility uti = new Utility();
    private DefaultTableModel modelketcau = new DefaultTableModel();
    private String ketcau="";
    /**
     * Creates new form KetCauJPanel
     */
    public KetCauJPanel(java.awt.Frame parent, boolean modal) {
        initComponents();
        modelketcau = (DefaultTableModel) tbl_ttketcau.getModel();
        tbl_ttketcau.setModel(modelketcau);
        showData(listKC = kcrepo.getKetCau());
    }
    
    private void showData(List<KetCau> list){
        modelketcau.setRowCount(0);
        
        for(KetCau ms : list){
            Object[] data = new Object[]{
                ms.getId(),ms.getTenketcau()
            };
            modelketcau.addRow(data);
        }
    }
    
    private void filldata(){
        List<KetCau> ms = kcrepo.getKetCau();
        modelketcau.setRowCount(0);
        for (KetCau object : kcrepo.getKetCau()) {
            modelketcau.addRow(new Object[]{object.getId(), object.getTenketcau()});
        }
        
    }
    
    private String getKC(int i){
        try {
            String ten="";
            ten=txt_ttKC.getText().trim();
            
            if(ten.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Nhap ketcau");
                return null;
            }else {
                return ten;
            }
            
        } catch (Exception e) {
            return null;
        }
        
    }
    
    public String getKetCau(){
        return ketcau;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnketcau = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_ttketcau = new javax.swing.JTable();
        lbl_mausac1 = new javax.swing.JLabel();
        btn_ttThemKC = new javax.swing.JButton();
        btn_ttClearKC = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_ttKC = new javax.swing.JTextField();
        txtkxID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnketcau.setBackground(new java.awt.Color(204, 204, 204));

        tbl_ttketcau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kết cấu"
            }
        ));
        tbl_ttketcau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ttketcauMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbl_ttketcau);

        lbl_mausac1.setText("Kết cấu");

        btn_ttThemKC.setText("Thêm");
        btn_ttThemKC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ttThemKCActionPerformed(evt);
            }
        });

        btn_ttClearKC.setText("Làm mới");
        btn_ttClearKC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ttClearKCActionPerformed(evt);
            }
        });

        jLabel14.setText("ID: ");

        jLabel15.setText("Kết cấu: ");

        txtkxID.setBackground(new java.awt.Color(204, 204, 204));
        txtkxID.setText("_ _");

        javax.swing.GroupLayout jpnketcauLayout = new javax.swing.GroupLayout(jpnketcau);
        jpnketcau.setLayout(jpnketcauLayout);
        jpnketcauLayout.setHorizontalGroup(
            jpnketcauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnketcauLayout.createSequentialGroup()
                .addGroup(jpnketcauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnketcauLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jpnketcauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ttThemKC)
                            .addComponent(btn_ttClearKC)))
                    .addGroup(jpnketcauLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jpnketcauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnketcauLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnketcauLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(28, 28, 28)))
                        .addGroup(jpnketcauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ttKC, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtkxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnketcauLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(lbl_mausac1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jpnketcauLayout.setVerticalGroup(
            jpnketcauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnketcauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_mausac1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnketcauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtkxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnketcauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_ttKC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnketcauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnketcauLayout.createSequentialGroup()
                        .addComponent(btn_ttThemKC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ttClearKC)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jpnketcau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnketcau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_ttketcauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ttketcauMouseClicked
        // TODO add your handling code here:
        int vitri = tbl_ttketcau.getSelectedRow();
        txtkxID.setText(String.valueOf(kcrepo.getKetCau().get(vitri).getId()));
        txt_ttKC.setText(kcrepo.getKetCau().get(vitri).getTenketcau());
    }//GEN-LAST:event_tbl_ttketcauMouseClicked

    private void btn_ttThemKCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ttThemKCActionPerformed
        // TODO add your handling code here:
         String tenKC = getKC(1);
        if(tenKC!=null){
            try {
                kcrepo.themKetCau(tenKC);
            } catch (Exception e) {
            }
            filldata();
            
        }

    }//GEN-LAST:event_btn_ttThemKCActionPerformed

    private void btn_ttClearKCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ttClearKCActionPerformed
        // TODO add your handling code here:
        txtkxID.setText("_ _");
        txt_ttKC.setText("");
    }//GEN-LAST:event_btn_ttClearKCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KetCauJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KetCauJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KetCauJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KetCauJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KetCauJPanel dialog = new KetCauJPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ttClearKC;
    private javax.swing.JButton btn_ttThemKC;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel jpnketcau;
    private javax.swing.JLabel lbl_mausac1;
    private javax.swing.JTable tbl_ttketcau;
    private javax.swing.JTextField txt_ttKC;
    private javax.swing.JTextField txtkxID;
    // End of variables declaration//GEN-END:variables
}
