/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.g4.view;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import com.g4.repository.impl.NhomHuongRepo;
import com.g4.entity.NhomHuong;
import com.g4.utils.Utility;
import java.util.ArrayList;
/**
 *
 * @author khuong duc
 */
public class NhomHuongJPanel extends javax.swing.JFrame {

    private NhomHuongRepo nhrepo = new NhomHuongRepo();
    private List<NhomHuong> listnh = new ArrayList<>();

    private Utility uti = new Utility();
    
    private DefaultTableModel modelnh = new DefaultTableModel();
    
    private String nhomhuong;
    /**
     * Creates new form NhomHuongJPanel
     */
    public NhomHuongJPanel(java.awt.Frame parent, boolean modal) {
        initComponents();
        
        modelnh = (DefaultTableModel) tbl_ttnhomhuong.getModel();
        tbl_ttnhomhuong.setModel(modelnh);
        showData(listnh = nhrepo.getNhomHuong());
    }
    
    private void showData(List<NhomHuong> list){
        modelnh.setRowCount(0);
        
        for(NhomHuong nh : list){
            Object[] data = new Object[]{
                nh.getId(),nh.getTenNhomHuong()
            };
            modelnh.addRow(data);
        }
    }
    private void filldata(){
        List<NhomHuong> ms = nhrepo.getNhomHuong();
        modelnh.setRowCount(0);
        for (NhomHuong object : nhrepo.getNhomHuong()) {
            modelnh.addRow(new Object[]{object.getId(), object.getTenNhomHuong()});
        }
        
    }
    private String getNH(int i){
        try {
            String ten="";
            ten=txt_ttNH.getText().trim();
            
            if(ten.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Nhap mau");
                return null;
            }else {
                return ten;
            }
            
        } catch (Exception e) {
            return null;
        }
        
    }
    
    public String getNhomHuong(){
        return nhomhuong;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnnhomhuong = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_ttnhomhuong = new javax.swing.JTable();
        lbl_nhomhuong = new javax.swing.JLabel();
        btn_ttThemNH = new javax.swing.JButton();
        btn_ttClearNH = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_ttNH = new javax.swing.JTextField();
        txtnhID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnnhomhuong.setBackground(new java.awt.Color(204, 204, 204));

        tbl_ttnhomhuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nhóm hương"
            }
        ));
        tbl_ttnhomhuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ttnhomhuongMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_ttnhomhuong);

        lbl_nhomhuong.setText("Nhóm hương");

        btn_ttThemNH.setText("Thêm");
        btn_ttThemNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ttThemNHActionPerformed(evt);
            }
        });

        btn_ttClearNH.setText("Làm mới");
        btn_ttClearNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ttClearNHActionPerformed(evt);
            }
        });

        jLabel17.setText("ID: ");

        jLabel18.setText("Nhóm hương: ");

        txtnhID.setText("_ _");

        javax.swing.GroupLayout jpnnhomhuongLayout = new javax.swing.GroupLayout(jpnnhomhuong);
        jpnnhomhuong.setLayout(jpnnhomhuongLayout);
        jpnnhomhuongLayout.setHorizontalGroup(
            jpnnhomhuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnnhomhuongLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_nhomhuong)
                .addGap(146, 146, 146))
            .addGroup(jpnnhomhuongLayout.createSequentialGroup()
                .addGroup(jpnnhomhuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnnhomhuongLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jpnnhomhuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ttThemNH)
                            .addComponent(btn_ttClearNH)))
                    .addGroup(jpnnhomhuongLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jpnnhomhuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addGap(8, 8, 8)
                        .addGroup(jpnnhomhuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ttNH, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnhID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jpnnhomhuongLayout.setVerticalGroup(
            jpnnhomhuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnnhomhuongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_nhomhuong, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnnhomhuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtnhID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnnhomhuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_ttNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnnhomhuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnnhomhuongLayout.createSequentialGroup()
                        .addComponent(btn_ttThemNH)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ttClearNH)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jpnnhomhuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnnhomhuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_ttnhomhuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ttnhomhuongMouseClicked
        // TODO add your handling code here:
        int vitri = tbl_ttnhomhuong.getSelectedRow();
        txtnhID.setText(String.valueOf(nhrepo.getNhomHuong().get(vitri).getId()));
        txt_ttNH.setText(nhrepo.getNhomHuong().get(vitri).getTenNhomHuong());
    }//GEN-LAST:event_tbl_ttnhomhuongMouseClicked

    private void btn_ttThemNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ttThemNHActionPerformed
            // TODO add your handling code here:
        String tennh = getNH(1);
        if(tennh!=null){
            try {
                nhrepo.themMau(tennh);
            } catch (Exception e) {
            }
            filldata();
            
        }
    }//GEN-LAST:event_btn_ttThemNHActionPerformed

    private void btn_ttClearNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ttClearNHActionPerformed
        // TODO add your handling code here:
        txtnhID.setText("_ _");
        txt_ttNH.setText("");
    }//GEN-LAST:event_btn_ttClearNHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhomHuongJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhomHuongJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhomHuongJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhomHuongJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MauSacJPanel dialog = new MauSacJPanel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ttClearNH;
    private javax.swing.JButton btn_ttThemNH;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel jpnnhomhuong;
    private javax.swing.JLabel lbl_nhomhuong;
    private javax.swing.JTable tbl_ttnhomhuong;
    private javax.swing.JTextField txt_ttNH;
    private javax.swing.JTextField txtnhID;
    // End of variables declaration//GEN-END:variables
}
